spring.application.name=campushub

spring.datasource.url=jdbc:postgresql://localhost:5432/campushub
spring.datasource.username=campushub
spring.datasource.password=campushub
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration