spring.datasource.url=jdbc:postgresql://localhost:5434/campushub_auth
spring.datasource.username=campushub
spring.datasource.password=campushub
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
